image: sknnr/necesse-dedicated-server
imageTag: latest
# serviceType should be LoadBalancer or NodePort
serviceType: LoadBalancer
resources:
  requests:
    memory: 8G
    cpu: 6.0
volumes:
  dataPVC:
    size: 50Gi
  storageClassName: ""
env:
  worldName: Necesse Kubernetes Server
  gamePort: 14159
  serverSlots: 10
  serverPassword: ""
  pauseEmpty: 0
  maxLatency: 30
  clientPower: 0
  langauge: en
  motd: ""
  logging: 1
  zipSaves: 1
  jvmArgs: ""
